# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam Shaukat
email: trautwebdev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Adam Shaukat is an actor based in New York City. He focuses on dramatic theater and is
  a student of the Yale School of Drama.
baseurl: "/shaukat"
url: "http://trautmaa.github.io"
twitter_username:
github_username:  trautmaa

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-coffeescript

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Sass
sass:
    sass_dir: _sass
    style: compressed
include: ['_pages']
kramdown:
  input: GFM

# Collections
collections:
- sections
